### PR TITLE
Label changed from ITA To SkilledTradesBC

### PR DESCRIPTION
**Pull request by rajavocette**
Label changed from ITA To SkilledTradesBC - Created new branch with latest packages

### CODE REVIEW

**Review by Rajandeep98 — APPROVED** [review]

**Comment by Rajandeep98** [comment]
changes in dev, waiting on test

**Comment by jpayoung** [comment]
Hi Team,

I have some concerns about the recent pull request to change the service name from "ITA Exam" to "SkilledTradesBC Exam." Some thoughts:

### 1. **Inconsistency**
Updating only the label without changing variable names creates inconsistencies, which could lead to confusion for future maintainers.

### 2. **Technical Debt**
Hardcoding service names instead of abstracting them can create more work in the future, with small changes requiring a large number of manual updates across the codebase.

### 3. **Code Readability and Maintainability**
Consistent naming conventions are crucial for code readability and maintainability. Mismatched names and labels can complicate understanding and maintaining the code.

### 4. Test Maintainability
Largely for the same reasons.

## Proposed Resolution
I'd propose also updating variable names to match the new service name. (I appreciate this will require a lot of work). I'm happy to take on this work.

In addition to that, I'm happy to rearchitect _where & how_ the type & name of the service is injected into other service components, which would - in my opinion - create a more scalable & maintainable long term solutions. I can append these changes to (#921) or open a new PR.

Thank you for your consideration.

J.P.

**Review by Rajandeep98 — APPROVED** [review]
database changes and variable name changes will be pushed in different PR. migrating CSRs to use skills trade. as its extremely old pr to be pushed to main.

**Review by josekudiyirippil — COMMENTED** [review]
change reviewed and looks ok

**Comment by jpayoung** [comment]
> database changes and variable name changes will be pushed in different PR. migrating CSRs to use skills trade. as its extremely old pr to be pushed to main.

Understood!

**Pull request merged**
