### PR TITLE
SBCQ-159 Cypress sample e2e test implementation

### PR DESCRIPTION
**Pull request by midhunmanoj2024**

### CODE REVIEW

**Comment by Rajandeep98** [comment]
able to pass the test
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  step1.cy.ts                              00:06        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:06        1        1        -        -        -

**Comment by Rajandeep98** [comment]
- add cypress run to scripts
- update patch

**Review by Rajandeep98 — COMMENTED** [review]
add cypress run to scripts
update patch

**Review by Rajandeep98 — APPROVED** [review]
Looks Good

**Review by josekudiyirippil — APPROVED** [review]
looks good

**Pull request merged**
